Document: amxa-webfs
Title: Debian amxa-webfs Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-webfs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-webfs/amxa-webfs.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-webfs/amxa-webfs.ps.gz

Format: text
Files: /usr/share/doc/amxa-webfs/amxa-webfs.text.gz

Format: HTML
Index: /usr/share/doc/amxa-webfs/html/index.html
Files: /usr/share/doc/amxa-webfs/html/*.html
